service: api-keys # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  profile: curso-sls
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  
  apiKeys:
  # vamos a poder cargar un archivo, dependiendo del envaronment
    - ${file(./config.${self:provider.stage}.json):API_KEY}

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: / # va a ser simplemente la raiz
        method: get
        private: true # de esta forma, necesitamos enviar la apikey para que el metodo funcione si no tira un error 404 Forbidden
